In [ ]:
import numpy as np

# **Comparing performance with lists**

In [ ]:
size = 10000

In [ ]:
%%time
ls = list(range(size))
for i in range(size):
    ls[i] = ls[i] * ls[i]

CPU times: user 4.55 ms, sys: 0 ns, total: 4.55 ms
Wall time: 4.86 ms


In [ ]:
%%time
ls_ = list(range(size))
ls_ = [item * item for item in ls_]

CPU times: user 1.12 ms, sys: 0 ns, total: 1.12 ms
Wall time: 1.13 ms


In [ ]:
%%time
list_ = list(range(size))
list_ = map(lambda x: x * x, list_)

CPU times: user 256 µs, sys: 0 ns, total: 256 µs
Wall time: 264 µs


In [ ]:
%%time
arr = np.arange(size)
arr = arr * arr

CPU times: user 535 µs, sys: 0 ns, total: 535 µs
Wall time: 458 µs


In [ ]:
range?

In [ ]:
np.arange?

# **Creating np Arrays**

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([0, 2, 4, 6, 8])

In [ ]:
print(arr, type(arr))

[0 2 4 6 8] <class 'numpy.ndarray'>


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr_ = np.array([0.0,2,4,6,8])

In [ ]:
print(arr_ , type(arr_))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [ ]:
arr_.dtype

dtype('float64')

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.size

6

In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.size

12

In [ ]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.56270796, -0.79777461,  0.82566091],
       [ 1.36601328, -0.31409611, -1.91539052]])

In [ ]:
np.random.rand(2, 3)

array([[0.87055274, 0.86270936, 0.80526507],
       [0.56696392, 0.38843435, 0.84011007]])

In [ ]:
np.random.randint(0, 100, (2, 3))

array([[86, 35, 65],
       [95, 65,  1]])

In [ ]:
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [ ]:
np.linspace?

In [ ]:
np.linspace(7, 70, 11)

array([ 7. , 13.3, 19.6, 25.9, 32.2, 38.5, 44.8, 51.1, 57.4, 63.7, 70. ])

In [ ]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [ ]:
str_arr = np.array([1.4, 2.1, 1.1])

In [ ]:
arr = np.array(str_arr, dtype='int')

In [ ]:
arr

array([1, 2, 1])

In [ ]:
arr2 = np.array([1,True,'happy'])

In [ ]:
print(arr2)

['1' 'True' 'happy']


In [ ]:
arr

array([1, 2, 1])

# **indexing**

In [ ]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [87]:
arr3d[0, 0, 0]

1

In [88]:
arr3d[1, 0, 2]

9

In [89]:
arr3d[1, :, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [90]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [91]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [92]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [93]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [94]:
arr3d[(arr3d % 2 == 1) & (arr3d > 5)]

array([ 7,  9, 11])

In [114]:
arr_slice = arr3d[:, :, 0:2]

In [115]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [116]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [117]:
arr_slice.ndim

3

In [118]:
arr_slice.shape

(2, 2, 2)

In [119]:
arr_slice[0, 0, 1]

2

In [120]:
arr_slice[0, 0, 0] = 598

In [121]:
arr_slice

array([[[598,   2],
        [  4,   5]],

       [[  7,   8],
        [ 10,  11]]])

In [122]:
arr3d

array([[[598,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [123]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [125]:
arr_slice

array([[[598,   2],
        [  4,   5]],

       [[  7,   8],
        [ 10,  11]]])

In [126]:
arr_slice[0, 0, 0] = 1

In [127]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [128]:
arr3d

array([[[598,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [129]:
arr = np.random.randint(0, 10, (5))

In [130]:
arr

array([6, 8, 7, 8, 1])

In [131]:
my_indices = [1, 3, 4]

In [132]:
arr[my_indices]

array([8, 8, 1])

# **Stat functions with NumPy**

In [133]:
arr = np.random.rand(1000,)

In [134]:
np.amin(arr)

0.0014591811163523483

In [135]:
np.amax(arr)

0.99914686265421

In [136]:
np.mean(arr)

0.48589697817894395

In [137]:
np.var(arr)

0.08179727863075123

In [138]:
np.std(arr)

0.2860022353597105

In [139]:
np.median(arr)

0.4787429977681991

In [140]:
np.percentile(arr, 50)

0.4787429977681991

In [141]:
np.percentile(arr, 10)

0.10146842205719385

In [142]:
np.percentile(arr, 90)

0.8876540601748856

In [144]:
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

In [145]:
print(iqr)

0.49645665700615715


In [ ]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

In [ ]:
print(quartiles)

In [ ]:
print(iqr)