In [72]:
import numpy as np
import pandas as pd

# **Series Object**

In [73]:
s = pd.Series([1, 2, 5, 7, 11 , 15, 18])

In [74]:
print(s)

0     1
1     2
2     5
3     7
4    11
5    15
6    18
dtype: int64


In [75]:
s = pd.Series([1.0, 2, 5, 7, 11, 15, 18])

In [76]:
print(s)

0     1.0
1     2.0
2     5.0
3     7.0
4    11.0
5    15.0
6    18.0
dtype: float64


In [77]:
s.values

array([ 1.,  2.,  5.,  7., 11., 15., 18.])

In [78]:
s.index

RangeIndex(start=0, stop=7, step=1)

In [79]:
for v in s.values:
    print(v)

1.0
2.0
5.0
7.0
11.0
15.0
18.0


In [80]:
for i in s.index:
    print(i)

0
1
2
3
4
5
6


In [81]:
for item in zip(s.index, s.values):
    print(item)

(0, 1.0)
(1, 2.0)
(2, 5.0)
(3, 7.0)
(4, 11.0)
(5, 15.0)
(6, 18.0)


In [82]:
s[0]

1.0

In [83]:
s[1]

2.0

In [84]:
s[5]

15.0

In [87]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=['mass', 'diameter', 'dayLength'])

In [88]:
print(mercury)

mass            0.33
diameter       57.90
dayLength    4222.60
dtype: float64


In [89]:
mercury['mass']

0.33

In [90]:
mercury['dayLength']

4222.6

In [91]:
mercury.mass

0.33

In [92]:
arr = np.random.randint(0, 10, 10)

In [93]:
arr

array([2, 5, 7, 9, 0, 0, 6, 5, 4, 6])

In [94]:
ind = np.arange(10, 20)

In [95]:
rand_series = pd.Series(arr, index=ind)

In [96]:
print(rand_series)

10    2
11    5
12    7
13    9
14    0
15    0
16    6
17    5
18    4
19    6
dtype: int64


In [97]:
# mercury = pd.Series([0.33, 57.9, 4222.6], index=['mass', 'diameter', 'dayLength'])

d = {}
d['mass'] = 0.33
d['diameter'] = 57.9
d['dayLength'] = 4222.6


In [98]:
print(d)

{'mass': 0.33, 'diameter': 57.9, 'dayLength': 4222.6}


In [100]:
mercury = pd.Series(d)

In [101]:
print(mercury)

mass            0.33
diameter       57.90
dayLength    4222.60
dtype: float64


In [102]:
mercury = pd.Series(d, index=['mass'])

In [103]:
print(mercury)

mass    0.33
dtype: float64


# **iloc and loc**

In [104]:
s = pd.Series([0, 11.0, 11.0, 22, 23, 5, 8], index=[1, 2, 3, 4, 5, 6, 7])

In [105]:
print(s)

1     0.0
2    11.0
3    11.0
4    22.0
5    23.0
6     5.0
7     8.0
dtype: float64


In [106]:
s.loc[4]

22.0

In [108]:
s.iloc[4]

23.0

In [109]:
s.iloc[0]

0.0

In [110]:
s.loc[0]

KeyError: ignored

In [111]:
mercury = pd.Series(d, index=['mass', 'diameter', 'dayLength'])

In [114]:
mercury

mass            0.33
diameter       57.90
dayLength    4222.60
dtype: float64

In [112]:
mercury.loc['mass']

0.33

In [115]:
mercury.iloc[0]

0.33

In [116]:
mercury.iloc[-1]

4222.6

In [117]:
mercury.iloc[0:1]

mass    0.33
dtype: float64

In [118]:
mercury.loc[:'dayLength']

mass            0.33
diameter       57.90
dayLength    4222.60
dtype: float64

#**DataFrames**

In [119]:
arr = np.random.randint(0, 10, (4, 3))

In [120]:
arr

array([[7, 2, 6],
       [0, 3, 9],
       [1, 1, 8],
       [5, 0, 4]])

In [121]:
df = pd.DataFrame(arr)

In [122]:
df

0  1  2
0  7  2  6
1  0  3  9
2  1  1  8
3  5  0  4

In [124]:
df[1][1]

3

In [125]:
df.values

array([[7, 2, 6],
       [0, 3, 9],
       [1, 1, 8],
       [5, 0, 4]])

In [126]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [127]:
df.index = ['R1', 'R2', 'R3', 'R4']
df.columns = ['C1', 'C2', 'C3']

In [128]:
df

C1  C2  C3
R1   7   2   6
R2   0   3   9
R3   1   1   8
R4   5   0   4

In [131]:
df.loc['R3':'R4', 'C2':'C3']

C2  C3
R3   1   8
R4   0   4

In [132]:
df.shape

(4, 3)

In [133]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146], 
                 index=['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])
diameter = pd.Series([4879, 12104, 12756, 3475, 6792, 142984, 120536, 51118, 49528, 2370], 
                     index=['Mercury', 'Venus', 'Earth', 'Moon', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])

In [134]:
df_ = pd.DataFrame({'Mass': mass, 'Diameter': diameter})

In [136]:
df_

Mass  Diameter
Earth       5.9700     12756
Jupiter  1898.0000    142984
Mars        0.6420      6792
Mercury     0.3300      4879
Moon           NaN      3475
Neptune   102.0000     49528
Pluto       0.0146      2370
Saturn    568.0000    120536
Uranus     86.8000     51118
Venus       4.8700     12104

In [137]:
df_['Mass']

Earth         5.9700
Jupiter    1898.0000
Mars          0.6420
Mercury       0.3300
Moon             NaN
Neptune     102.0000
Pluto         0.0146
Saturn      568.0000
Uranus       86.8000
Venus         4.8700
Name: Mass, dtype: float64

In [138]:
df_['Diameter']

Earth       12756
Jupiter    142984
Mars         6792
Mercury      4879
Moon         3475
Neptune     49528
Pluto        2370
Saturn     120536
Uranus      51118
Venus       12104
Name: Diameter, dtype: int64

In [144]:
df_['temp'] = 0

In [145]:
df_

Mass  Diameter  temp
Earth       5.9700     12756     0
Jupiter  1898.0000    142984     0
Mars        0.6420      6792     0
Mercury     0.3300      4879     0
Moon           NaN      3475     0
Neptune   102.0000     49528     0
Pluto       0.0146      2370     0
Saturn    568.0000    120536     0
Uranus     86.8000     51118     0
Venus       4.8700     12104     0

In [149]:
df_.drop('temp',axis = 1 ,inplace=True)

In [151]:
df_

Mass  Diameter
Earth       5.9700     12756
Jupiter  1898.0000    142984
Mars        0.6420      6792
Mercury     0.3300      4879
Moon           NaN      3475
Neptune   102.0000     49528
Pluto       0.0146      2370
Saturn    568.0000    120536
Uranus     86.8000     51118
Venus       4.8700     12104